### ISSUE TITLE
Not Working in Sketch V41

### ISSUE THREAD

**Issue by brandonkboswell** [poyi/Copy-Fill-Color#10]

**Comment by montemartin** [comment]
+1. I need to rename layers with the hex code of their fill. This plugin is exactly what I set out looking for but it isn't working. If there is no fill I get an error message, but if there is a fill it doesn't populate the clipboard. Let me know if I can provide any other info to help get it working again.

**Comment by hugomagallanes** [comment]
+1 It's really a shame! Before updating to the lasted version (v41), I was using it all the time. Can you please look into it?

**Comment by poyi** [comment]
thanks for opening up the issue. I haven't got around to test the latest sketch update. will investigate.

**Comment by poyi** [comment]
@brandonkboswell @montemartin @hugomagallanes Just resolved the issue. One of the function to grab color was removed as part of the new updates. I tested against the latest version and it should work now. 

Cheers,

**Comment by montemartin** [comment]
@poyi works great thanks!
