### ISSUE TITLE
Paste Fill Color

### ISSUE THREAD

**Issue by gingerbeardman** [poyi/Copy-Fill-Color#2]
Please add Paste Fill Color

**Comment by poyi** [comment]
I imagine this is to paste/apply the copied fill color to another layer. Sounds useful and can look into supporting that.

**Comment by poyi** [comment]
@gingerbeardman, there is a Sketch shortcut for copying and pasting all styles form one element to another. Think it suits the functionality you're looking for.

`option + cmd + c`
`option + cmd +v`

A link to a tips and tricks article, see #1 https://medium.com/@assentorp/10-sketch-tricks-you-need-to-know-as-a-designer-bfba9e7ec137

Closing this issue for now.
