### ISSUE TITLE
Plugin folder location for Mac App Store version 

### ISSUE THREAD

**Issue by toddprouty** [poyi/Copy-Fill-Color#4]
It looks like you have the incorrect location for the plugin folder used by the Mac App Store version, at least in Yosemite. Here's what worked for me:

`~/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins`

**Comment by poyi** [comment]
You're right, the Yosemite path is different. Will update the installation info, thanks!

Library ▸ Containers ▸ com.bohemiancoding.sketch3 ▸ Data ▸ Library ▸ Application Support ▸ com.bohemiancoding.sketch3 ▸ Plugins
