### ISSUE TITLE
Not working in 3.4.3

### ISSUE THREAD

**Issue by katrinkerber** [poyi/Copy-Fill-Color#9]
Running version 3.4.3 on OSX 10.10.5 and none of the shortcuts/commands copy anything to the clipboard.

**Comment by iamhenry** [comment]
Yup. Not working for me either. Would love an update for this please.

**Comment by poyi** [comment]
It is not working per the latest updates. Will take a look.

**Comment by poyi** [comment]
@katrinkerber & @iamhenry should work now, please check.
